### ISSUE TITLE
Mandei pra uma menina mas ela me xingou

### ISSUE THREAD

**Issue by victormn** [vmarchesin/vemdezapbe.be#1]
**Versão do site:** não achei
**Frase usada:** QUER TC COMIGO 😈😼👉👌😋 BB?
**Resposta esperada:** Claro :)
**Resposta recebida:** (melhor não colar aqui)

**Comment by vmarchesin** [comment]
Tente mudar a versão da menina, só funciona com meninas `v5.0` ou abaixo.
