### ISSUE TITLE
Faltou licença livre

### ISSUE THREAD

**Issue by nicolasmaia** [vmarchesin/vemdezapbe.be#3]
Ficou faltando. Recomendo AGPL!

**Comment by vmarchesin** [comment]
A GPL 3.0 já está em vigor no repositório há algum tempo, e supre todas as necessidades (o código pode ser compartilhado e modificado livremente, desde que de forma aberta e documentada). Dadas as implicações deste software não vejo vantagem em trocar para a AGPL.

Você pode tentar me convencer do contrário.

**Comment by nicolasmaia** [comment]
Tranquilo, qualquer licença livre é boa. Eu só dei uma olhada rápida e vi que não tinha LICENSE.md, por isso o issue

**Comment by vmarchesin** [comment]
Sem problemas. A licença foi adicionada no commit [1e3a8a0](https://github.com/vmarchesin/vemdezapbe.be/commit/1e3a8a0635b58a5cda305300a05fc4595a489852).
