### ISSUE TITLE
API Quebra (Internal server error 500) com requests sem User-Agent

### ISSUE THREAD

**Issue by Kasama** [vmarchesin/vemdezapbe.be#5]
Se é realizada uma request sem o Header `User-Agent`, ou com ele nulo, a API retorna um erro 500, sem explicação do problema.

O problema é causado pois na linha https://github.com/vmarchesin/vemdezapbe.be/blob/master/app.js#L78.
```javascript
const validPost = req.headers["user-agent"].match("Mozilla") && (data.rate === undefined || Number(data.rate) >= 0.3)
```
O código tenta acessar a função `match` do `user-agent`, que é inexistente no caso sem user-agent.

Não entendi o propósito inicial dessa verificação de `User-Agent` conter `Mozilla`

**Comment by vmarchesin** [comment]
Fiz a verificação inicialmente para filtrar chamadas feitas através de um browser (uma vez que a maioria dos browsers hoje em dia são [Mozzilla compatible](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Headers/User-Agent)). Isso foi feito para evitar que uma api externa fosse capaz de publicar no twitter.

Esqueci de fazer a verificação no caso de não existir o header.

**Comment by Kasama** [comment]
Eu fiz o pull request #6  que deve resolver isso. Ele não publica no twitter caso o `User-Agent` seja não-mozilla

**Comment by vmarchesin** [comment]
Pensando bem não faz muito sentido mesmo essa verificação, ela funcionou pro seu propósito na hora, mas ainda é possível fazer um User-Agent falso na request de uma API e enviar para o twitter. O propósito foi primariamente evitar publicações feitas via API já que o usuário geralmente não vai ter a opção de consentir com a publicação da mensagem (como num bot do Telegram por exemplo).

Pode editar o seu commit pra remover a verificação totalmente? Realmente não faz sentido uma vez que ela pode ser forjada. Sobe um novo Pull Request e eu já aprovo.

**Comment by Kasama** [comment]
posso sim, vou fazer isso e te dou um ping.
Estou fazendo um [bot pra telegram](https://github.com/Kasama/zapeador-bot) (aproveitando pra aprender haskell) e tava tendo problema com o `user-agent`

**Comment by Kasama** [comment]
@vmarchesin feito, dá uma olhada lá no PR #7

**Comment by vmarchesin** [comment]
Feito! Como o deploy é automático você pode testar as mudanças em alguns minutos no seu bot e ver se o problema foi resolvido. Obrigado pelo achado!
