### ISSUE TITLE
Meu feedback.

### ISSUE THREAD

**Issue by EduApps-CDG** [vmarchesin/vemdezapbe.be#9]
Estou 😆 usando 😄😋😉 sua API 😆😛😄 para um gerador de textos de um bot 😄 do Discord devido 😄😊😎 a sugestão 😜😜😄 de um usuário. 😝😅😀 E, consequentemente, acabou 😁😊😉 disfarçando alguns 😝 erros do gerador. Valeu 😛 ai pela 😂👌😄 ideia! 😀
![image](https://user-images.githubusercontent.com/32627482/150952965-67e5fde9-3e5d-40f7-bda4-d2f7a75f6575.png)

**Comment by vmarchesin** [comment]
E aí, fico feliz que esteja usando a API 😁 Mas faz tempo que não mexo nesse código, fiz praticamente tudo em 3 dias lá em 2018 e não mexi na composição desde então 😅. Se quiser fazer pode fazer um PR, ou então você é livre para fazer um fork e hostear em um serviço próprio. 

A API está rodando numa instância gratuita do Heroku, se quiser é bem fácil de hospedar o seu serviço. Mas se quiser fazer um PR eu não tenho a intenção de tirar o serviço do ar, então pode ser mais fácil. Mas não vou corrigir nenhum erro já que não mantenho mais esse repositório. Se fizer uma contribuição significativa posso te adicionar como contribuidor se quiser continuar usando este repo 😃

**Comment by EduApps-CDG** [comment]
Vou dar uma checada no código :+1:
